#!/usr/bin/env bash
# Script for automating correction of configuration issues

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
