#!/usr/bin/env bash
# displays FizzBuzz when the number is a multiple of 3 and 5
# displays Fizz when the number is a multiple of 3
# displays Buzz when the number is a multiple of 5
# else, displays the number in a list format
num=1
while [ $num -le 100 ]
do
	if [ $((num % 5)) == 0 ] && [ $((num % 3)) == 0 ]
	then
		echo "FizzBuzz"
	elif [ $((num % 3)) == 0 ]
	then
		echo "Fizz"
	elif [ $((num % 5)) == 0 ]
	then
		echo "Buzz"
	else
		echo "$num"
	fi
	num=$(( num + 1 ))
done
