#!/usr/bin/env bash
# Bash script displays Best School 10 times.
# but for the 9th, displays Best School and the Hi.
t=1
while [ $t -le 10 ]
do
    if [ $t = 10 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    t=$(( t+=1 ))
done
