#!/usr/bin/env bash
# loop from 1 to 10 and:
# display bad luck for the 4th element
# display good luck for the 8th element
# display Best School for the other elements
element=1
while [ $element -le 10 ]
do
	if [ $element = 4 ]
	then
		echo "bad luck"
	elif [ $element = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	element=$(( element + 1 ))
done
